# Generated by Django 3.1 on 2020-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocalendar', '0003_auto_20200907_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='modified_by',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
