# Generated by Django 3.1 on 2020-09-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocalendar', '0005_event_read_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='supervisor_read',
            field=models.BooleanField(default=False),
        ),
    ]
