# Generated by Django 3.1 on 2020-09-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocalendar', '0007_auto_20200914_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Reject'), ('SEND_BACK', 'Send_Back'), ('INITIAL', 'Initial'), ('FORM SENT', 'Form Sent')], default='INITIAL', max_length=512),
        ),
    ]
