# Generated by Django 3.0.8 on 2020-07-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chlorinated_Soft_Water_Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1', 'Chlorinated_Soft_Water_Tank')], max_length=20)),
                ('doc_no', models.CharField(max_length=10)),
                ('ref_sop_no', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('equipment_code', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('frequency', models.CharField(max_length=20)),
                ('sr_no', models.IntegerField()),
                ('activity', models.CharField(choices=[('1', 'SMBS chemical dosing tank cleaning (T-965A)'), ('2', 'SMBS dosing pump, pipe, float switch, leakage from NRV to check. Attend, if any'), ('3', 'Chlorinated water pump ( Motor connection tightening, earthing connections,motor pump guard, M-seal leakage, note motor ampere withdrawn'), ('4', 'Motor bearing and pump guard condition'), ('5', 'Water leakage from M-seal or connected like connection. Attend if any'), ('6', 'Chlorine sensor transmitter calibration as per calibration plan'), ('7', 'Chlroine sensor housing leakage, membrane/electrolye replacement (when ever required'), ('8', 'Tank top ( dome) cleaning work')], max_length=200)),
                ('done_notdone', models.CharField(choices=[('1', 'Done'), ('2', 'Not Done')], max_length=20)),
                ('remarks', models.TextField(max_length=400)),
                ('done_by', models.CharField(max_length=20)),
                ('checked_by', models.CharField(max_length=40)),
                ('done_on', models.DateTimeField(max_length=40)),
                ('next_due_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Electrical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
