# Generated by Django 3.0.8 on 2020-07-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='frequency',
            field=models.CharField(choices=[('1', 'Daily'), ('2', 'Weekly'), ('3', 'Monthly'), ('4', 'Quarterly'), ('5', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=20),
        ),
    ]
