# Generated by Django 3.0.8 on 2020-07-29 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0003_auto_20200729_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 29, 8, 46, 9, 698942)),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 8, 46, 9, 698942)),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='next_due_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 8, 46, 9, 698942)),
        ),
    ]
