# Generated by Django 3.0.8 on 2020-08-05 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0005_auto_20200731_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='status',
            field=models.CharField(choices=[('1', 'PENDING'), ('2', 'ACCEPTED'), ('3', 'REJECTED')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 5, 9, 41, 42, 35652)),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 9, 41, 42, 35652)),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='next_due_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 9, 41, 42, 35652)),
        ),
    ]
