# Generated by Django 3.0.8 on 2020-08-06 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0007_auto_20200806_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 6, 10, 40, 40, 538401)),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 10, 40, 40, 538401)),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='next_due_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 10, 40, 40, 538401)),
        ),
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 10, 40, 40, 539400)),
        ),
    ]
