# Generated by Django 3.0.8 on 2020-08-07 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0008_auto_20200806_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chlorinated_soft_water_tank',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='chlorinated_soft_water_tank',
            name='done_notdone',
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='remark_smbs',
            field=models.TextField(default='No Remarks', max_length=100),
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='smbs',
            field=models.CharField(default='Not Done', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 7, 9, 54, 19, 44609)),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 9, 54, 19, 44609)),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='next_due_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 9, 54, 19, 44609)),
        ),
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 9, 54, 19, 45610)),
        ),
    ]
