# Generated by Django 3.0.8 on 2020-08-07 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0009_auto_20200807_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chlorinated_soft_water_tank',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 7, 9, 58, 22, 894695)),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 9, 58, 22, 894695)),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='next_due_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 9, 58, 22, 894695)),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='remark_smbs',
            field=models.TextField(default='No Remarks', max_length=50),
        ),
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 9, 58, 22, 895695)),
        ),
    ]
