# Generated by Django 3.0.8 on 2020-08-07 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0010_auto_20200807_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 12, 56, 21, 860084)),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='location',
            field=models.CharField(default='Sanand,Gujarat', max_length=50),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='January', max_length=20),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='next_due_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 12, 56, 21, 860084)),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='title',
            field=models.CharField(default='Chlorinated_Soft_Water_Tank', max_length=200),
        ),
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 12, 56, 21, 861120)),
        ),
    ]
