# Generated by Django 3.0.8 on 2020-08-07 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0012_auto_20200807_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='done_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='frequency',
            field=models.CharField(default='Monthly', max_length=200),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='next_due_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 14, 42, 27, 908738)),
        ),
    ]
