# Generated by Django 3.0.8 on 2020-08-07 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0013_auto_20200807_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='chl_sns_transmitter',
            field=models.CharField(default='chl_sns_transmitter', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='chl_water_pump',
            field=models.CharField(default='chl_water_pump', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='chlorine_sensor',
            field=models.CharField(default='chlorine_sensor', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='motor_bearing',
            field=models.CharField(default='motor_bearing', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='remark_chl_sns_transmitter',
            field=models.TextField(default='No Remarks', max_length=50),
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='remark_chl_water_pump',
            field=models.TextField(default='No Remarks', max_length=50),
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='remark_chlorine_sensor',
            field=models.TextField(default='No Remarks', max_length=50),
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='remark_dosing_pump',
            field=models.TextField(default='No Remarks', max_length=50),
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='remark_motor_bearing',
            field=models.TextField(default='No Remarks', max_length=50),
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='remark_tank_top',
            field=models.TextField(default='No Remarks', max_length=50),
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='remark_water_leakage',
            field=models.TextField(default='No Remarks', max_length=50),
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='smbs_dosing_pump',
            field=models.CharField(default='smbs_dosin_pump', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='tank_top',
            field=models.CharField(default='tank_top', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chlorinated_soft_water_tank',
            name='water_leakage',
            field=models.CharField(default='water_leakage', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 15, 2, 49, 215717)),
        ),
    ]
