# Generated by Django 3.0.8 on 2020-08-07 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0014_auto_20200807_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='remark_chl_sns_transmitter',
            field=models.CharField(default='No Remarks', max_length=50),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='remark_chl_water_pump',
            field=models.CharField(default='No Remarks', max_length=50),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='remark_chlorine_sensor',
            field=models.CharField(default='No Remarks', max_length=50),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='remark_dosing_pump',
            field=models.CharField(default='No Remarks', max_length=50),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='remark_motor_bearing',
            field=models.CharField(default='No Remarks', max_length=50),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='remark_smbs',
            field=models.CharField(default='No Remarks', max_length=50),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='remark_tank_top',
            field=models.CharField(default='No Remarks', max_length=50),
        ),
        migrations.AlterField(
            model_name='chlorinated_soft_water_tank',
            name='remark_water_leakage',
            field=models.CharField(default='No Remarks', max_length=50),
        ),
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 15, 35, 42, 312116)),
        ),
    ]
