# Generated by Django 3.1 on 2020-08-11 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0015_auto_20200807_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 9, 58, 58, 720660)),
        ),
    ]
