# Generated by Django 3.1 on 2020-08-11 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0016_auto_20200811_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 11, 44, 10, 254933)),
        ),
    ]
