# Generated by Django 3.1 on 2020-08-18 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0019_auto_20200817_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 17, 31, 52, 562492)),
        ),
    ]
