# Generated by Django 3.1 on 2020-08-20 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0026_auto_20200820_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 15, 10, 53, 675245)),
        ),
    ]
