# Generated by Django 3.1 on 2020-08-25 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0031_auto_20200824_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 15, 34, 52, 110551)),
        ),
    ]
