# Generated by Django 3.1 on 2020-09-02 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0036_auto_20200902_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 15, 1, 51, 204109)),
        ),
    ]
