# Generated by Django 3.1 on 2020-09-07 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0047_auto_20200907_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 19, 33, 33, 120529)),
        ),
    ]
