# Generated by Django 3.1 on 2020-09-09 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0053_auto_20200908_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 13, 27, 14, 490338)),
        ),
    ]
