# Generated by Django 3.1 on 2020-09-09 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0054_auto_20200909_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 13, 33, 27, 526931)),
        ),
    ]
