# Generated by Django 3.1 on 2020-09-10 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogbook', '0057_auto_20200910_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_sheet_pcc',
            name='done_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 16, 58, 15, 500788)),
        ),
    ]
