# Generated by Django 3.0.8 on 2020-07-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200727_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('ASSOCIATE', 'Associate'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Admin')], max_length=15),
        ),
    ]
