# Generated by Django 3.1 on 2020-09-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200819_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
