# Generated by Django 3.1 on 2020-08-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=512)),
                ('user', models.CharField(max_length=200)),
                ('sent_by', models.CharField(max_length=300)),
            ],
        ),
    ]
