# Generated by Django 3.1 on 2020-08-19 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test', '0006_delete_department'),
        ('sanand_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.form'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
