# Generated by Django 3.1 on 2020-08-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanand_calendar', '0005_auto_20200820_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='submit_by',
            field=models.DateField(auto_now=True),
        ),
    ]
