# Generated by Django 3.1 on 2020-08-06 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('created_by', models.CharField(default='', editable=False, max_length=255)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('modified_by', models.CharField(default='', editable=False, max_length=255)),
                ('field_name', models.CharField(blank=True, max_length=512)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('CHOICE', 'Choice'), ('DROPDOWN', 'Dropdown')], max_length=512)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('created_by', models.CharField(default='', editable=False, max_length=255)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('modified_by', models.CharField(default='', editable=False, max_length=255)),
                ('form_name', models.CharField(blank=True, max_length=512)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('category', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('created_by', models.CharField(default='', editable=False, max_length=255)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('modified_by', models.CharField(default='', editable=False, max_length=255)),
                ('option_name', models.CharField(blank=True, max_length=512)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test.field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test.form'),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('created_by', models.CharField(default='', editable=False, max_length=255)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('modified_by', models.CharField(default='', editable=False, max_length=255)),
                ('form_data', models.JSONField(default=dict)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
