# Generated by Django 3.1 on 2020-08-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_auto_20200811_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='option_type',
            field=models.CharField(choices=[('RADIO_BUTTON', 'Radio_button'), ('TEXT', 'Text')], default='None', max_length=512),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('CHOICE', 'Choice'), ('CHOICE+REMARK', 'Choice+Remark'), ('DROPDOWN', 'Dropdown')], max_length=512),
        ),
    ]
