# Generated by Django 3.1 on 2020-08-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_auto_20200811_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_value',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
