# Generated by Django 3.1 on 2020-08-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_field_field_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('created_by', models.CharField(default='', editable=False, max_length=255)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('modified_by', models.CharField(default='', editable=False, max_length=255)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
