# Generated by Django 3.1 on 2020-08-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
