# Generated by Django 3.1 on 2020-08-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_delete_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='form',
        ),
        migrations.AddField(
            model_name='form',
            name='field',
            field=models.ManyToManyField(blank=True, to='test.Field'),
        ),
    ]
