# Generated by Django 3.1 on 2020-08-24 11:40

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import *


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_auto_20200824_1612'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='form',
            name='field',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='test.Field'),
        ),
    ]
