# Generated by Django 3.1 on 2020-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0009_auto_20200825_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='form_remarks',
        ),
        migrations.RemoveField(
            model_name='form',
            name='status',
        ),
        migrations.AddField(
            model_name='data',
            name='form_remarks',
            field=models.TextField(default='No Remarks', max_length=1000),
        ),
        migrations.AddField(
            model_name='data',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Reject'), ('SEND_BACK', 'Send_Back')], default='Send_Back', max_length=512),
        ),
    ]
