# Generated by Django 3.1 on 2020-09-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0010_auto_20200825_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='form_remarks',
        ),
        migrations.RemoveField(
            model_name='data',
            name='status',
        ),
    ]
