# Generated by Django 3.1 on 2020-09-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocalendar', '0003_auto_20200907_1824'),
        ('test', '0011_auto_20200907_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='form',
        ),
        migrations.RemoveField(
            model_name='data',
            name='user',
        ),
        migrations.AddField(
            model_name='data',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangocalendar.event'),
        ),
    ]
