# Generated by Django 3.1 on 2020-09-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0012_auto_20200907_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='field',
        ),
    ]
