# Generated by Django 3.1 on 2020-09-10 10:47

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0013_remove_options_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='options',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='test.Options'),
        ),
    ]
